### ISSUE TITLE
sureflap

### ISSUE THREAD

**Issue by sirkubax** [tinuva/home-assistant-config#1]
Hello, 
good work!

Not sure how to contact you, so I'd do it via this ticket.

Do I understand correctly, that SureFlap Connect Door does not require SureFlap Connect HUB (https://www.surepetcare.com/en-gb/internet-hub/hub)

I'm about to buy doors, and I wonder what is minimum hardware requirement to access door statistics. I don't mind buying a hub too :)

**Comment by tinuva** [comment]
Hey,

You do require the hub to use it with your phone or if you want to use it with home assistant. 
Without the hub, the petdoor function as if it is the normal non-connection version without phone control.

**Comment by sirkubax** [comment]
Thanks.
I was hoping that it is already possible to connect to the doors directly :)
