### ISSUE TITLE
sure petcare individual pet permissions?

### ISSUE THREAD

**Issue by tm1m1tw** [tinuva/home-assistant-config#2]
I am getting ready to integrate the work that you expanded on in order to set the door mode but I was wondering if it were also possible to set individual pet permissions? I.e. Change Pet A to indoor cat from indoor/outdoor while keeping Pet B and C and indoor/outdoor.

I am looking to lock specific pets inside when their GPS tracking collar falls below a certain %

**Comment by tinuva** [comment]
Unfortunately I do not think it is possible to lock the door for only specific pets. When it is unlocked for going out, it even allows pets without tags to go out. The tag reader seems to only work for letting pets in when unlocked.

You can also test all the different combinations on the website: https://surepetcare.io/

If that website has the feature, it is something you can implement.

The other problem I have is, the locking/unlocking happens really slow, most of the time, for me it is only actioned about a minute later, so it would be difficult to even try a work around.

I think if you want a feature like this, you definitely need to raise it with the company. Looks like you can start a discussion here: https://sureflapsupport.force.com/support/s/topic/0TOa0000000PwSbGAK/connected-products?language=en_US
